# Generated by Django 5.1.3 on 2024-12-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_delete_blogpost"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="BlogPost",
        ),
    ]
